"""Integration tests for the eager mini-summary on ``entity(action='resolve')``.

Covers bead ``scix_experiments-3lw4.1``: ``co_occurring`` and
``recent_examples`` fields folded into resolver candidates so callers can
triage without an immediate ``entity_context`` follow-up.

Tests seed a small graph into ``entities`` + ``papers`` +
``document_entities`` (the source table for the canonical matview), refresh
``document_entities_canonical``, and then exercise the helper directly and
through ``_handle_entity``. The matview rebuild is fast on ``scix_test``
(<100 rows) but skipped cleanly when ``SCIX_TEST_DSN`` is not configured
(production DSN is rejected).
"""

from __future__ import annotations

import json
from collections.abc import Iterator
from typing import Any

import psycopg
import pytest

from scix.entity_eager_summary import fetch_entity_mini_summaries
from scix.mcp_server import _handle_entity
from tests.helpers import get_test_dsn

# Stable string prefix used across all seeded rows so teardown can remove
# only the rows this fixture created. Test entity ids are generated by the
# entities sequence; we capture them in the fixture and pass them down.
_BIB_PREFIX = "TEST-EAGER-SUM-"
_ENTITY_NAME_PREFIX = "TestEagerSum-"
_ENTITY_SOURCE = "test-eager-sum"


def _cleanup(conn: psycopg.Connection) -> None:
    """Remove any rows this fixture may have created on prior runs."""
    conn.rollback()
    with conn.cursor() as cur:
        cur.execute(
            "DELETE FROM document_entities WHERE bibcode LIKE %s",
            (f"{_BIB_PREFIX}%",),
        )
        cur.execute(
            "DELETE FROM papers WHERE bibcode LIKE %s",
            (f"{_BIB_PREFIX}%",),
        )
        cur.execute(
            "DELETE FROM entities WHERE source = %s",
            (_ENTITY_SOURCE,),
        )
    conn.commit()
    # Refresh the matview so leftover seeded rows from a crashed prior run
    # do not show up in helper queries before we re-seed.
    with conn.cursor() as cur:
        cur.execute("REFRESH MATERIALIZED VIEW document_entities_canonical")
    conn.commit()


def _seed(conn: psycopg.Connection) -> dict[str, int]:
    """Seed a small entity-co-occurrence graph for the test cases.

    Layout:
      Entity FOCAL -- appears in 5 papers (P1..P5)
      Entity COA   -- appears in P1, P2, P3 (3 shared with FOCAL)
      Entity COB   -- appears in P1, P2          (2 shared with FOCAL)
      Entity COC   -- appears in P1               (1 shared, below threshold)
      Entity ISOLATED -- appears only in its own paper (P_ISO),
                         no overlap with FOCAL.

    Returns a dict mapping logical name -> entity_id.
    """
    with conn.cursor() as cur:
        # Insert entities first so we get back the auto-generated ids.
        # entity_type values are picked from the production enum list so
        # any downstream constraints behave the same way they do in prod.
        names = ["FOCAL", "COA", "COB", "COC", "ISOLATED"]
        types = ["method", "method", "dataset", "instrument", "method"]
        ids: dict[str, int] = {}
        for n, t in zip(names, types):
            cur.execute(
                """
                INSERT INTO entities
                  (canonical_name, entity_type, source)
                VALUES (%s, %s, %s)
                RETURNING id
                """,
                (f"{_ENTITY_NAME_PREFIX}{n}", t, _ENTITY_SOURCE),
            )
            ids[n] = cur.fetchone()[0]

        # Papers: P1..P5 spread across years so recent_examples ordering
        # has meaningful signal (year DESC).
        # P_ISO is for the ISOLATED entity only.
        papers = [
            (f"{_BIB_PREFIX}P1", "Paper 1", 2025),
            (f"{_BIB_PREFIX}P2", "Paper 2", 2024),
            (f"{_BIB_PREFIX}P3", "Paper 3", 2023),
            (f"{_BIB_PREFIX}P4", "Paper 4", 2022),
            (f"{_BIB_PREFIX}P5", "Paper 5", 2021),
            (f"{_BIB_PREFIX}P_ISO", "Isolated Paper", 2020),
        ]
        for bib, title, year in papers:
            cur.execute(
                "INSERT INTO papers (bibcode, title, year) VALUES (%s, %s, %s)",
                (bib, title, year),
            )

        # document_entities links. Use confidence=0.9 and tier=0 so the
        # matview's fusion math produces a non-zero fused_confidence.
        # link_type='instance' is a generic value that satisfies the NOT
        # NULL constraint without depending on a specific harvester.
        de_rows = [
            # FOCAL appears in P1..P5
            ("FOCAL", "P1"),
            ("FOCAL", "P2"),
            ("FOCAL", "P3"),
            ("FOCAL", "P4"),
            ("FOCAL", "P5"),
            # COA shares 3 papers with FOCAL
            ("COA", "P1"),
            ("COA", "P2"),
            ("COA", "P3"),
            # COB shares 2 papers with FOCAL (at threshold)
            ("COB", "P1"),
            ("COB", "P2"),
            # COC shares 1 paper with FOCAL (below default threshold)
            ("COC", "P1"),
            # ISOLATED has its own paper, no overlap with FOCAL.
            ("ISOLATED", "P_ISO"),
        ]
        for ename, pname in de_rows:
            cur.execute(
                """
                INSERT INTO document_entities
                  (bibcode, entity_id, link_type, confidence, tier, tier_version)
                VALUES (%s, %s, 'instance', 0.9, 0, 1)
                """,
                (f"{_BIB_PREFIX}{pname}", ids[ename]),
            )

    conn.commit()

    # Refresh the matview so the seeded rows propagate to
    # document_entities_canonical (the helper reads this matview, not
    # document_entities directly).
    with conn.cursor() as cur:
        cur.execute("REFRESH MATERIALIZED VIEW document_entities_canonical")
    conn.commit()

    return ids


@pytest.fixture()
def seeded_conn() -> Iterator[tuple[psycopg.Connection, dict[str, int]]]:
    """Yield a connection with the test graph seeded; clean up after."""
    dsn = get_test_dsn()
    if dsn is None:
        pytest.skip("SCIX_TEST_DSN not set or points at production")
    conn = psycopg.connect(dsn)
    conn.autocommit = False
    try:
        _cleanup(conn)
        ids = _seed(conn)
        yield conn, ids
    finally:
        try:
            _cleanup(conn)
        finally:
            conn.close()


# ---------------------------------------------------------------------------
# Helper-level tests (fetch_entity_mini_summaries)
# ---------------------------------------------------------------------------


def test_helper_empty_input_returns_empty_dict() -> None:
    """No DB call needed when entity_ids is empty; helper returns {}."""
    # Pass a None-ish connection to prove the helper short-circuits before
    # touching it.
    result = fetch_entity_mini_summaries(None, [])  # type: ignore[arg-type]
    assert result == {}


def test_helper_co_occurring_top_k_and_threshold(
    seeded_conn: tuple[psycopg.Connection, dict[str, int]],
) -> None:
    """FOCAL gets COA (3 shared) and COB (2 shared); COC (1 shared) drops."""
    conn, ids = seeded_conn
    summaries = fetch_entity_mini_summaries(
        conn,
        [ids["FOCAL"]],
        co_occur_min=2,
        co_occur_top_k=3,
        recent_top_k=2,
    )
    co = summaries[ids["FOCAL"]]["co_occurring"]
    assert co is not None
    names = [c["canonical_name"] for c in co]
    assert f"{_ENTITY_NAME_PREFIX}COA" in names
    assert f"{_ENTITY_NAME_PREFIX}COB" in names
    assert f"{_ENTITY_NAME_PREFIX}COC" not in names, "below-threshold should drop"
    # COA must outrank COB on shared_papers count.
    coa_idx = names.index(f"{_ENTITY_NAME_PREFIX}COA")
    cob_idx = names.index(f"{_ENTITY_NAME_PREFIX}COB")
    assert coa_idx < cob_idx
    # shared_papers is the count of co-occurrences in the sampled paper set.
    coa_row = co[coa_idx]
    cob_row = co[cob_idx]
    assert coa_row["shared_papers"] == 3
    assert cob_row["shared_papers"] == 2


def test_helper_recent_examples_orders_by_year_desc(
    seeded_conn: tuple[psycopg.Connection, dict[str, int]],
) -> None:
    """Recent examples come back year-DESC, capped at recent_top_k=2."""
    conn, ids = seeded_conn
    summaries = fetch_entity_mini_summaries(
        conn,
        [ids["FOCAL"]],
        recent_top_k=2,
    )
    recent = summaries[ids["FOCAL"]]["recent_examples"]
    assert recent is not None
    assert len(recent) == 2
    years = [r["year"] for r in recent]
    assert years == sorted(years, reverse=True)
    # The most-recent FOCAL paper is P1 (year=2025).
    assert recent[0]["bibcode"] == f"{_BIB_PREFIX}P1"
    assert recent[0]["year"] == 2025
    assert recent[0]["title"] == "Paper 1"


def test_helper_absent_data_emits_null_not_empty_list(
    seeded_conn: tuple[psycopg.Connection, dict[str, int]],
) -> None:
    """ISOLATED has no co-occurrences -> co_occurring is None, not []."""
    conn, ids = seeded_conn
    summaries = fetch_entity_mini_summaries(
        conn,
        [ids["ISOLATED"]],
        co_occur_min=2,
    )
    assert summaries[ids["ISOLATED"]]["co_occurring"] is None
    # ISOLATED still has its own paper, so recent_examples is non-empty.
    recent = summaries[ids["ISOLATED"]]["recent_examples"]
    assert recent is not None
    assert recent[0]["bibcode"] == f"{_BIB_PREFIX}P_ISO"


def test_helper_unknown_entity_id_keys_present_with_nulls(
    seeded_conn: tuple[psycopg.Connection, dict[str, int]],
) -> None:
    """Unknown entity_ids must still appear in the result dict, both fields null."""
    conn, _ = seeded_conn
    bogus = -999_999
    summaries = fetch_entity_mini_summaries(conn, [bogus])
    assert summaries[bogus] == {"co_occurring": None, "recent_examples": None}


def test_helper_high_threshold_drops_all_co_occurring(
    seeded_conn: tuple[psycopg.Connection, dict[str, int]],
) -> None:
    """A precision-style filter that empties the field surfaces None."""
    conn, ids = seeded_conn
    # No co-occurring entity shares >=10 papers with FOCAL in this seed.
    summaries = fetch_entity_mini_summaries(
        conn,
        [ids["FOCAL"]],
        co_occur_min=10,
    )
    assert summaries[ids["FOCAL"]]["co_occurring"] is None
    # recent_examples is unaffected by the co-occur threshold.
    assert summaries[ids["FOCAL"]]["recent_examples"] is not None


def test_helper_batched_query_handles_multiple_focals(
    seeded_conn: tuple[psycopg.Connection, dict[str, int]],
) -> None:
    """One round trip enriches both FOCAL and ISOLATED with their own data."""
    conn, ids = seeded_conn
    summaries = fetch_entity_mini_summaries(conn, [ids["FOCAL"], ids["ISOLATED"]])
    assert ids["FOCAL"] in summaries
    assert ids["ISOLATED"] in summaries
    assert summaries[ids["FOCAL"]]["co_occurring"] is not None
    assert summaries[ids["ISOLATED"]]["co_occurring"] is None


# ---------------------------------------------------------------------------
# End-to-end tests via _handle_entity
# ---------------------------------------------------------------------------


def _resolve(conn: psycopg.Connection, query: str) -> dict[str, Any]:
    return json.loads(
        _handle_entity(
            conn,
            {"action": "resolve", "query": query, "fuzzy": False},
        )
    )


def test_resolve_response_includes_mini_summary_fields(
    seeded_conn: tuple[psycopg.Connection, dict[str, int]],
) -> None:
    """Each candidate row exposes co_occurring and recent_examples keys."""
    conn, _ = seeded_conn
    parsed = _resolve(conn, f"{_ENTITY_NAME_PREFIX}FOCAL")
    cands = parsed.get("candidates", [])
    # Resolver must return at least the seeded FOCAL row.
    assert any(c["canonical_name"] == f"{_ENTITY_NAME_PREFIX}FOCAL" for c in cands)
    for c in cands:
        assert "co_occurring" in c
        assert "recent_examples" in c
    focal = next(c for c in cands if c["canonical_name"] == f"{_ENTITY_NAME_PREFIX}FOCAL")
    assert focal["co_occurring"] is not None
    assert focal["recent_examples"] is not None
    # Sanity: top co-occurring entity is COA per the seed.
    assert focal["co_occurring"][0]["canonical_name"] == f"{_ENTITY_NAME_PREFIX}COA"
    # Recent examples ordered year DESC.
    assert focal["recent_examples"][0]["bibcode"] == f"{_BIB_PREFIX}P1"


def test_resolve_response_emits_null_for_isolated_entity(
    seeded_conn: tuple[psycopg.Connection, dict[str, int]],
) -> None:
    """An entity with no co-occurrences surfaces co_occurring=null."""
    conn, _ = seeded_conn
    parsed = _resolve(conn, f"{_ENTITY_NAME_PREFIX}ISOLATED")
    iso = next(
        c
        for c in parsed.get("candidates", [])
        if c["canonical_name"] == f"{_ENTITY_NAME_PREFIX}ISOLATED"
    )
    assert iso["co_occurring"] is None
    # ISOLATED still has its own paper as a recent example.
    assert iso["recent_examples"] is not None
    assert iso["recent_examples"][0]["bibcode"] == f"{_BIB_PREFIX}P_ISO"
