#!/usr/bin/env python3
"""Diff community labels before/after the dbl.6 vocab-boost rerun.

Reads the pre-run snapshot CSV (written before kicking off
``generate_community_labels.py --signal semantic --allow-prod``) and the
post-run rows from the live ``communities`` table, then writes a
markdown side-by-side for the 10 largest communities at each resolution
plus the random spot-check sample selected by the script itself.

Used to satisfy the acceptance criterion in bead ``scix_experiments-dbl.6``:
"Spot-check: 10 communities show qualitatively better labels".
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import psycopg


def _read_before(csv_path: Path) -> dict[tuple[str, str, int], tuple[str, list[str]]]:
    out: dict[tuple[str, str, int], tuple[str, list[str]]] = {}
    with csv_path.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            key = (row["signal"], row["resolution"], int(row["community_id"]))
            kw = row["top_keywords"].strip("{}")
            kws = [k.strip('"') for k in kw.split(",")] if kw else []
            out[key] = (row["label"], kws)
    return out


def _read_after(dsn: str, signal: str) -> dict[tuple[str, str, int], tuple[str, list[str], int]]:
    out: dict[tuple[str, str, int], tuple[str, list[str], int]] = {}
    with psycopg.connect(dsn) as c, c.cursor() as cur:
        cur.execute(
            "SELECT signal, resolution, community_id, label, top_keywords, paper_count "
            "FROM communities WHERE signal = %s "
            "ORDER BY signal, resolution, community_id",
            (signal,),
        )
        for s, r, cid, label, kws, pc in cur:
            out[(s, r, cid)] = (label, list(kws or []), pc)
    return out


def _format_section(before: dict, after: dict, resolution: str, top_n: int) -> list[str]:
    lines: list[str] = []
    lines.append(f"## semantic / {resolution} (top {top_n} by paper_count)\n")
    relevant = [(key, val) for key, val in after.items() if key[1] == resolution]
    relevant.sort(key=lambda kv: -kv[1][2])
    for key, (after_label, after_kws, paper_count) in relevant[:top_n]:
        before_entry = before.get(key)
        before_label = before_entry[0] if before_entry else "(missing)"
        before_kws = before_entry[1] if before_entry else []
        cid = key[2]
        lines.append(f"### community_id={cid}  (paper_count={paper_count:,})\n")
        lines.append(f"- **Before**: {before_label}")
        lines.append("- **Before keywords**: " + ", ".join(f"`{k}`" for k in before_kws[:10]))
        lines.append(f"- **After**:  {after_label}")
        lines.append("- **After keywords**:  " + ", ".join(f"`{k}`" for k in after_kws[:10]))
        lines.append("")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dsn", default="dbname=scix")
    parser.add_argument(
        "--before-csv",
        default="/tmp/community_labels_before_dbl6.csv",
    )
    parser.add_argument(
        "--out",
        default="docs/prd/artifacts/community_labels_dbl6_diff.md",
    )
    parser.add_argument("--top-n", type=int, default=10)
    args = parser.parse_args()

    before_path = Path(args.before_csv)
    if not before_path.exists():
        raise SystemExit(f"missing pre-run snapshot at {before_path}")

    before = _read_before(before_path)
    after = _read_after(args.dsn, "semantic")

    out_lines: list[str] = []
    out_lines.append("# Community-label diff (bead scix_experiments-dbl.6)\n")
    out_lines.append(
        "Generated by `scripts/dbl6_label_diff.py`. Compares the "
        "semantic-partition labels before and after the vocab-boost "
        "rerun of `scripts/generate_community_labels.py`. The boost "
        "multiplies the TF-IDF score of any term that matches a known "
        "concept across the ingested vocabularies (MeSH, Gene Ontology, "
        "ChEBI, ACM CCS, MSC, PhySH, GCMD, OpenAlex Topics, NCBI "
        "Taxonomy).\n"
    )
    for resolution in ("coarse", "medium", "fine"):
        out_lines.extend(_format_section(before, after, resolution, args.top_n))

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(out_lines))
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
